version: "3"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - 4444:4444

  chrome-node:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true

  app:
    image: webratio/ant:1.10.1
    working_dir: /application
    volumes:
      - .:/application:cached
    depends_on:
      - chrome-node
    command: "ant testng-chrome-grid"

